backend:
  name: git-gateway
  branch: master

media_folder: "src/assets/images/min" # Folder where user uploaded files should go
public_folder: "/assets/images/min" # Folder where user uploaded files should go

collections: # A list of collections the CMS should be able to edit
  - label: "Pages"
    name: "home"
    files:
      - label: "Global"
        name: "global"
        file: "_data/global/global.yml"
        fields:
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields:
              - {label: Primary, name: primary, widget: string}
              - {label: Secondary, name: secondary, widget: string}
              - {label: Third, name: third, widget: string}
              - {label: Fourth, name: fourth, widget: string}
              - {label: Fifth, name: fifth, widget: string}
          - {label: Brand, name: brand, widget: string, hint: "Brand Name"}
          - label: "Social" 
            name: "social" 
            allow_add: true
            widget: "list"
            fields:
              - {label: Icon Class, name: icon, widget: string}
              - {label: Name, name: name, widget: string}
              - {label: Href, name: href, widget: string}
              - {label: Button Class, name: btn, widget: string}
              - {label: Class, name: class, widget: string, default: 'icon-1'}
      - label: "Home Page"
        name: "home"
        file: "_data/home/home.yml"
        widget: "object"
        fields:
          - label: SEO
            name: seo
            widget: object
            fields:
              - {label: SEO Title, name: title, widget: string}
              - {label: SEO Description, name: description, widget: string}
          - label: Header
            name: header
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - label: "Header Image"
                name: "backgroundImage"
                widget: "image"
                default: "/images/header-bg.jpg"
              - label: Button
                name: button
                widget: object
                fields:
                  - {label: Text, name: text, widget: string}
                  - {label: href, name: href, widget: string, default: '#about'}
          - label: "About us"
            name: about
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: 'About us'}
              - {label: Content, name: content, widget: text}
          - label: "Services"
            name: services
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: 'Services'}
              - {label: Subtitle, name: subtitle, widget: string, default: 'What we do'}
              - label: "Background Image"
                name: "backgroundImage"
                widget: "image"
                default: "/images/services-bg.jpg"
              - {label: Content, name: content, widget: text}
              - label: "Items" 
                name: "items" 
                allow_add: true
                widget: "list"
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Icon?, name: fa, widget: select, options: ["true", "false"], default: "false"}
                  - {label: Icon Class, name: icon, widget: string}
                  - label: "Image"
                    name: "image"
                    widget: "image"
                    required: false
                  - {label: Resize, name: resize, widget: string, hint: '[70]', required: false}
                  - {label: Content, name: content, widget: text}
          - label: "Portfolio"
            name: portfolio
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: 'See Our Featured Projects.'}
              - {label: Subtitle, name: subtitle, widget: string, default: 'Showcase'}
              - {label: Content, name: content, widget: text}
              - label: "Items" 
                name: "items" 
                allow_add: true
                widget: "list"
                fields:
                  - {label: Subtitle, name: subtitle, widget: string}
                  - {label: Title, name: title, widget: string}
                  - {label: Src, name: src, widget: image, hint: "bigger file size"}
                  - {label: Link, name: link, widget: string,  required: false}
                  - {label: Content, name: content, widget: text,  required: false}
          - label: "Testimonials"
            name: testimonials
            widget: object
            fields:
              - {label: Title, name: title, widget: string, default: 'See Our Featured Projects.'}
              - label: "Items" 
                name: "items" 
                allow_add: true
                widget: "list"
                fields:
                  - {label: Avatar, name: avatar, widget: image}
                  - {label: Name, name: name, widget: string}
                  - {label: Position, name: position, widget: string}
                  - {label: Content, name: content, widget: text}
          - label: "Clients"
            name: clients
            widget: list
            allow_add: true
            fields:
              - {label: Src, name: src, widget: image}
              - {label: Resize, name: resize, widget: string, hint: '70x70', required: false}
              - {label: Alt, name: alt, widget: string}
          - label: Contact
            name: contact
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - label: "Background Image"
                name: "backgroundImage"
                widget: "image"
                default: "/images/contact-bg.jpg"
              - {label: Button, name: actionTitle, widget: string}
              - {label: Content, name: content, widget: text}
              - label: Form
                name: form
                widget: object
                fields:
                  - {label: action, name: action, widget: string}
              - label: Information
                name: information
                widget: object
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Subtitle, name: subtitle, widget: string}
                  - {label: Address, name: address, widget: text}
                  - {label: Email title, name: emailTitle, widget: string}
                  - {label: Emails, name: emails, widget: text}
                  - {label: Phone title, name: phoneTitle, widget: string}
                  - {label: Phones, name: phones, widget: text}
      - label: "Footer"
        name: "footer"
        file: "_data/footer/footer.yml"
        fields:
          - {label: Brand, name: brand, widget: string}
          - {label: Content, name: content, widget: text}
          - {label: Newsletter Title, name: newsletterTitle, widget: string, default: 'Get Notified'}
          - {label: Newsletter Content, name: newsletterContent, widget: text}